### ISSUE TITLE
Evaluation for more datasets

### ISSUE THREAD

**Issue by Lauch1ng** [TRI-ML/vlm-evaluation#7]
Hello, will you support evaluation for more benchmarks (e.g., MME)? Thanks a lot!

**Comment by ashwin-balakrishna96** [comment]
We are definitely working on adding more evaluation benchmarks, and [MME](https://arxiv.org/html/2306.13394v4) would definitely be a great one. If you would be interested in adding support for any more benchmarks and opening up a PR, we would also be happy to review and add it in any evaluations. Thanks!
